# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install
          command: yarn install

      - run:
          name: Update dependencies
          command: yarn add codecov -D

      - save_cache:
      # https://circleci.com/docs/2.0/configuration-reference/#save_cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Compile typescript
          command: yarn run ts

      - run:
          name: Invoke code coverage tools
          command: npx istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec

      - run:
          name: Upload code coverage
          command: npx codecov
